# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: My PRs
    filters: is:open author:@me
    layout:
      author:
        hidden: true
      authorIcon:
        hidden: true
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
notificationsSections:
  - title: Unread
    filters: is:unread
  - title: Participating
    filters: reason:participating
  - title: Review Requested
    filters: reason:review-requested
defaults:
  view: prs
  preview:
    open: false
    width: 0.5
  prsLimit: 20
  issuesLimit: 20
  notificationsLimit: 20
  prApproveComment: LGTM
  refetchIntervalMinutes: 30
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 20
      assignees:
        hidden: true
      base:
        hidden: true
    issues:
      updatedAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 12
      assignees:
        hidden: true
keybindings:
  universal:
    - key: enter
      builtin: togglePreview
  prs:
    - key: g
      name: lazygit
      command: cd {{.RepoPath}} && lazygit
    - key: t
      name: tuicr review
      command: tuicr pr {{.RepoName}}#{{.PrNumber}}
    - key: R
      name: rerun failed jobs
      command: gh run rerun -R {{.RepoName}} --failed $(gh run list -R {{.RepoName}} -b {{.HeadRefName}} -s failure -L 1 --json databaseId --jq '.[0].databaseId')
repoPaths:
  craftworkco/*: ~/Dev/*
  drucial/*: ~/Dev/*
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#e0def4"
      secondary: "#c4a7e7"
      inverted: "#232136"
      faint: "#a5a1bc"
      warning: "#f6c177"
      success: "#9ccfd8"
      error: "#eb6f92"
      actor: "#ea9a97"
    background:
      selected: "#2a283e"
    border:
      primary: "#56526e"
      secondary: "#44415a"
      faint: "#393552"
    icon:
      newcontributor: "#9ccfd8"
      contributor: "#ea9a97"
      collaborator: "#f6c177"
      member: "#c4a7e7"
      owner: "#eb6f92"
      unknownrole: "#6e6a86"
pager:
  diff: diffnav
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: false
