#!/usr/bin/env sh

# Only trap SIGTERM and SIGINT, not EXIT
trap cleanup SIGTERM SIGINT

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Function to apply Yabai configuration settings
apply_yabai_config() {
  local yabai_config=(
    -m config

    layout bsp
    auto_balance off
    split_ratio 0.50

    insert_feedback_color 0xff9dd274

    focus_follows_mouse off
    mouse_follows_focus off
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap

    top_padding 16
    bottom_padding 16
    left_padding 16
    right_padding 16
    window_gap 16

    window_placement second_child
    window_shadow float
    window_zoom_persist off
    window_animation_duration 0.3
    window_animation_easing ease_out_quint
  )

  yabai "${yabai_config[@]}"
}

# function to add application-specific rules
add_yabai_rules() {

  # exclude specific applications from being managed
  apps_to_exclude=(
    "^calculator$"
    "^Software Update$"
    "^Dictionary$"
    "^System Preferences$"
    "^System Settings$"
    "^Finder$"
    "^System Information"
    "^Archive Utility$"
    "^App Store$"
    "^Raycast$"
    "^activity monitor$"
    "^Messages$"
    "^Facetime$"
    "^Logi Options+$"
    "^Tuple$"
    "^Postgres$"
    "^CleanShot X$"
    "^EVO$"
  )

   # --- ChatGPT-specific rules ---
  # Exclude the companion popup (sticky/system dialog)
  yabai -m rule --add app="ChatGPT" subrole="AXSystemDialog" manage=off
  # Allow the main app window to be tiled/managed
  yabai -m rule --add app="ChatGPT" subrole="AXStandardWindow" layer=normal manage=on

  for app in "${apps_to_exclude[@]}"; do
    yabai -m rule --add app="$app" manage=off
  done

  # Global Rules
  yabai -m rule --add app=".*" sub-layer=normal
  yabai -m rule --apply
}

# apply configuration and rules
apply_yabai_config
add_yabai_rules

echo "yabai configuration loaded..."
