windowrulev2 = workspace 1,class:^(chrome-app\.slack\.com.*)$
windowrulev2 = workspace 1,class:^(chrome-mail\.superhuman\.com.*)$
windowrulev2 = workspace 1,class:^(chrome-calendar\.notion\.so.*)$
windowrulev2 = workspace 2,class:^(chrome-linear\.app.*)$
windowrulev2 = workspace 3,class:^(chrome-www\.notion\.so.*)$
windowrulev2 = workspace 4,class:^(chromium|zen)$
windowrulev2 = workspace 5,class:^([Cc]ode)$
windowrulev2 = workspace 5,class:^(chrome-github\.com.*)$
windowrulev2 = workspace 6,class:^([Kk]itty)$
windowrulev2 = workspace 7,class:^(chrome-figma\.com.*)$
windowrulev2 = workspace 8,class:^(chrome-youtube\.com.*)$
windowrulev2 = workspace 9,class:^(chrome-chatgpt\.com.*)$
windowrulev2 = workspace 10,class:^(Spotify)$
