return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "helix",
    icons = { mappings = false, rules = false, group = "" },
    plugins = { spelling = { suggestions = 10 } },
    spec = {
      { "<leader>b", group = "buffer" },
      { "<leader>c", group = "code" },
      { "<leader>d", group = "diagnostics" },
      { "<leader>f", group = "find" },
      { "<leader>g", group = "git" },
      { "<leader>s", group = "surround" },
      { "<leader>sd", group = "delete surround" },
      { "<leader>sc", group = "change surround" },
      { "g", group = "goto" },
      { "gc", group = "comment" },
      { "gr", group = "lsp" },
      { "gO", desc = "Document symbols" },
      { "gra", desc = "Code action" },
      { "grn", desc = "Rename symbol" },
      { "grr", desc = "References" },
      { "gri", desc = "Implementations" },
      { "grt", desc = "Type definition" },
      { "grx", desc = "Run codelens" },
      { "]a", desc = "Next file in arglist" },
      { "[a", desc = "Previous file in arglist" },
      { "]A", desc = "Last file in arglist" },
      { "[A", desc = "First file in arglist" },
      { "]b", desc = "Next buffer" },
      { "[b", desc = "Previous buffer" },
      { "]B", desc = "Last buffer" },
      { "[B", desc = "First buffer" },
      { "]l", desc = "Next loclist item" },
      { "[l", desc = "Previous loclist item" },
      { "]L", desc = "Last loclist item" },
      { "[L", desc = "First loclist item" },
      { "]q", desc = "Next quickfix item" },
      { "[q", desc = "Previous quickfix item" },
      { "]Q", desc = "Last quickfix item" },
      { "[Q", desc = "First quickfix item" },
      { "]t", desc = "Next tag" },
      { "[t", desc = "Previous tag" },
      { "]T", desc = "Last tag" },
      { "[T", desc = "First tag" },
      { "]<C-l>", desc = "Next loclist file" },
      { "[<C-l>", desc = "Previous loclist file" },
      { "]<C-q>", desc = "Next quickfix file" },
      { "[<C-q>", desc = "Previous quickfix file" },
      { "]<C-t>", desc = "Next tag in preview" },
      { "[<C-t>", desc = "Previous tag in preview" },
      { "gx", desc = "Open file or URI under cursor" },
    },
  },
}
