# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --syntax-theme base16-256 --file-decoration-style=""
gui:
  nerdFontsVersion: "3"
  filterMode: fuzzy
  showNumstatInFilesView: true
  showDivergenceFromBaseBranch: arrowAndNumber
