# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  theme:
    selectedLineBgColor:
      - black
    activeBorderColor:
      - blue
  nerdFontsVersion: "3"
  filterMode: fuzzy
  showNumstatInFilesView: true
  showDivergenceFromBaseBranch: arrowAndNumber
